//notification
export const FETCHING_NOTIFICATION = 'FETCHING_NOTIFICATION';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';

//saved
export const FETCHING_SAVED = 'FETCHING_SAVED';
export const FETCH_SAVED_SUCCESS = 'FETCH_SAVED_SUCCESS';
export const FETCH_SAVED_FAILURE = 'FETCH_SAVED_FAILURE';

//ARTICLE
export const FETCHING_ARTICLE = 'FETCHING_ARTICLE';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

//PLAYLIST
export const FETCHING_PLAYLIST = 'FETCHING_PLAYLIST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE';
