//saved
export const FETCHING_SAVED = 'FETCHING_SAVED';
export const FETCH_SAVED_SUCCESS = 'FETCH_SAVED_SUCCESS';
export const FETCH_SAVED_FAILURE = 'FETCH_SAVED_FAILURE';

//ARTICLE
export const FETCHING_ARTICLE = 'FETCHING_ARTICLE';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

//PLAYLIST
export const FETCHING_PLAYLIST = 'FETCHING_PLAYLIST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE';

//ONBOARDING
export const FETCHING_ONBOARDING = 'FETCHING_ONBOARDING';
export const FETCH_ONBOARDING_SUCCESS = 'FETCH_ONBOARDING_SUCCESS';
export const FETCH_ONBOARDING_FAILURE = 'FETCH_ONBOARDING_FAILURE';

//USERHIGHLIGHT
export const FETCHING_USER_HIGHLIGHT = 'FETCHING_USER_HIGHLIGHT';
export const FETCH_USER_HIGHLIGHT_SUCCESS = 'FETCH_USER_HIGHLIGHT_SUCCESS';
export const FETCH_USER_HIGHLIGHT_FAILURE = 'FETCH_USER_HIGHLIGHT_FAILURE';


//GETUSERPROFILE
export const FETCHING_USER_PROFILE = 'FETCHING_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

//GETUSERNAME
export const FETCHING_USER_NAME = 'FETCHING_USER_NAME';
export const FETCH_USER_NAME_SUCCESS = 'FETCH_USER_NAME_SUCCESS';
export const FETCH_USER_NAME_FAILURE = 'FETCH_USER_NAME_FAILURE';

//UPDATEUSERPROFILE
export const UPDATING_USER_PROFILE = 'UPDATING_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';

//GETUSERANALYST
export const FETCHING_USER_ANALYST = 'FETCHING_USER_ANALYST';
export const FETCH_USER_ANALYST_SUCCESS = 'FETCH_USER_ANALYST_SUCCESS';
export const FETCH_USER_ANALYST_FAILURE = 'FETCH_USER_ANALYST_FAILURE';

//LAST_READING_POSITION
export const FETCHING_LAST_READING_POSITION = 'FETCHING_LAST_READING_POSITION';
export const FETCH_LAST_READING_POSITION_SUCCESS = 'FETCH_LAST_READING_POSITION_SUCCESS';
export const FETCH_LAST_READING_POSITION_FAILURE = 'FETCH_LAST_READING_POSITION_FAILURE';

//GETUSERPATH
export const FETCHING_USER_PATH = 'FETCHING_USER_PATH';
export const FETCH_USER_PATH_SUCCESS = 'FETCH_USER_PATH_SUCCESS';
export const FETCH_USER_PATH_FAILURE = 'FETCH_USER_PATH_FAILURE';

//GETSOURCELIST
export const FETCHING_SOURCE_LIST = 'FETCHING_SOURCE_LIST';
export const FETCH_SOURCE_LIST_SUCCESS = 'FETCH_SOURCE_LIST_SUCCESS';
export const FETCH_SOURCE_LIST_FAILURE = 'FETCH_SOURCE_LIST_FAILURE';

//GETTOPICLIST
export const FETCHING_TOPIC_LIST = 'FETCHING_TOPIC_LIST';
export const FETCH_TOPIC_LIST_SUCCESS = 'FETCH_TOPIC_LIST_SUCCESS';
export const FETCH_TOPIC_LIST_FAILURE = 'FETCH_TOPIC_LIST_FAILURE';

//UPDATESOURCES
export const UPDATING_USER_SOURCES = 'UPDATING_USER_SOURCES';
export const UPDATE_USER_SOURCES_SUCCESS = 'UPDATE_USER_SOURCES_SUCCESS';
export const UPDATE_USER_SOURCES_FAILURE = 'UPDATE_USER_SOURCES_FAILURE';

//UPDATESOURCES
export const UPDATING_USER_TOPIC = 'UPDATING_USER_TOPIC';
export const UPDATE_USER_TOPIC_SUCCESS = 'UPDATE_USER_TOPIC_SUCCESS';
export const UPDATE_USER_TOPIC_FAILURE = 'UPDATE_USER_TOPIC_FAILURE';

//GET INTENTIONS
export const FETCHING_INTENT = 'FETCHING_INTENT';
export const FETCH_INTENT_SUCCESS = 'FETCH_INTENT_SUCCESS';
export const FETCH_INTENT_FAILURE = 'FETCH_INTENT_FAILURE';

//GET ALL INTENTIONS
export const FETCHING_ALL_INTENT = 'FETCHING_ALL_INTENT';
export const FETCH_ALL_INTENT_SUCCESS = 'FETCH_ALL_INTENT_SUCCESS';
export const FETCH_ALL_INTENT_FAILURE = 'FETCH_ALL_INTENT_FAILURE';

//GET PATH_RECOMMEND
export const FETCHING_PATH_RECOMMEND = 'FETCHING_PATH_RECOMMEND';
export const FETCH_PATH_RECOMMEND_SUCCESS = 'FETCH_PATH_RECOMMEND_SUCCESS';
export const FETCH_PATH_RECOMMEND_FAILURE = 'FETCH_PATH_RECOMMEND_FAILURE';

//GET PATH_BOOKMARKED
export const FETCHING_PATH_BOOKMARKED = 'FETCHING_PATH_BOOKMARKED';
export const FETCH_PATH_BOOKMARKED_SUCCESS = 'FETCH_PATH_BOOKMARKED_SUCCESS';
export const FETCH_PATH_BOOKMARKED_FAILURE = 'FETCH_PATH_BOOKMARKED_FAILURE';

//GET PATH_CURRENT
export const FETCHING_PATH_CURRENT = 'FETCHING_PATH_CURRENT';
export const FETCH_PATH_CURRENT_SUCCESS = 'FETCH_PATH_CURRENT_SUCCESS';
export const FETCH_PATH_CURRENT_FAILURE = 'FETCH_PATH_CURRENT_FAILURE';

// UPDATE_RECOMMEND_SOURE
export const UPDATING_RECOMMEND_SOURE = 'UPDATING_RECOMMEND_SOURE';
export const UPDATE_RECOMMEND_SOURE_SUCCESS = 'UPDATE_RECOMMEND_SOURE_SUCCESS';
export const UPDATE_RECOMMEND_SOURE_FAILURE = 'UPDATE_RECOMMEND_SOURE_FAILURE';

//UPDATE_TAG
export const UPDATE_USER_SOURCE_TAG = 'UPDATE_USER_SOURCE_TAG';

// TRACKING USERKIT EVENT
export const TRACK_USERKIT_EVENT = 'TRACK_USERKIT_EVENT';

// CREATE BOOKMARK
export const CREATING_BOOKMARK = 'CREATING_BOOKMARK';
export const CREATE_BOOKMARK_SUCCESS = 'CREATE_BOOKMARK_SUCCESS';
export const CREATE_BOOKMARK_FAILURE = 'CREATE_BOOKMARK_FAILURE';

// REMOVE BOOKMARK
export const REMOVING_BOOKMARK = 'REMOVING_BOOKMARK';
export const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS';
export const REMOVE_BOOKMARK_FAILURE = 'REMOVE_BOOKMARK_FAILURE';

// GET WATCHING HISTORY
export const FETCHING_WATCHING_HISTORY = 'FETCHING_WATCHING_HISTORY';
export const FETCH_WATCHING_HISTORY_SUCCESS = 'FETCH_WATCHING_HISTORY_SUCCESS';
export const FETCH_WATCHING_HISTORY_FAILURE = 'FETCH_WATCHING_HISTORY_FAILURE';

// GET CONTINUE READING
export const FETCHING_CONTINUE_READING = 'FETCHING_CONTINUE_READING';
export const FETCH_CONTINUE_READING_SUCCESS = 'FETCH_CONTINUE_READING_SUCCESS';
export const FETCH_CONTINUE_READING_FAILURE = 'FETCH_CONTINUE_READING_FAILURE';

export const FETCHING_CATEGORY = 'FETCHING_CATEGORY';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';

// GET FEED
export const FETCHING_FEED = 'FETCHING_FEED';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';
export const FETCH_FEED_FAILURE = 'FETCH_FEED_FAILURE';

// GET SAVEDIDS
export const FETCHING_BOOKMARKEDIDS = 'FETCHING_BOOKMARKEDIDS';
export const FETCH_BOOKMARKEDIDS_SUCCESS  = 'FETCH_BOOKMARKEDIDS_SUCCESS';
export const FETCH_BOOKMARKEDIDS_FAILURE = 'FETCH_BOOKMARKEDIDS_FAILURE';

//GET CONTRIBUTOR LIST
export const FETCHING_CONTRIBUTOR_LIST = 'FETCHING_CONTRIBUTOR_LIST';
export const FETCH_CONTRIBUTOR_LIST_SUCCESS = 'FETCH_CONTRIBUTOR_LIST_SUCCESS';
export const FETCH_CONTRIBUTOR_LIST_FAILURE = 'FETCH_CONTRIBUTOR_LIST_FAILURE';

//UPDATE CONTRIBUTOR FOLLOW
export const UPDATE_USER_CONTRIBUTOR_FOLLOW = 'UPDATE_USER_CONTRIBUTOR_FOLLOW';
export const UPDATE_USER_CONTRIBUTOR_FOLLOW_SUCCESS = 'UPDATE_USER_CONTRIBUTOR_FOLLOW_SUCCESS';
export const UPDATE_USER_CONTRIBUTOR_FOLLOW_FAILURE = 'UPDATE_USER_CONTRIBUTOR_FOLLOW_FAILURE';

// HIGHLIGHT
export const CREATING_USER_HIGHLIGHT = 'CREATE_USER_HIGHLIGHT';
export const CREATE_USER_HIGHLIGHT_SUCCESS = 'CREATE_USER_HIGHLIGHT_SUCCESS';
export const CREATE_USER_HIGHLIGHT_FAILURE = 'CREATE_USER_HIGHLIGHT_FAILURE';

// CREATE USER
export const CREATING_USER = 'CREATING_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

// FOLLOW PERSONAS
export const UPDATING_FOLLOW_PERSONA = 'UPDATING_FOLLOW_PERSONA';
export const UPDATE_FOLLOW_PERSONA_SUCCESS = 'UPDATE_FOLLOW_PERSONA_SUCCESS';
export const UPDATE_FOLLOW_PERSONA_FAILURE = 'UPDATE_FOLLOW_PERSONA_FAILURE';

// OWNPATH
export const FETCHING_OWNPATH = '';
export const FETCH_OWNPATH_SUCCESS = 'FETCH_OWNPATH_SUCCESS';
export const FETCH_OWNPATH_FAILURE = 'FETCH_OWNPATH_FAILURE';

// FETCH ARTICLE DETAIL
export const FETCHING_ARTICLE_DETAIL = 'FETCHING_ARTICLE_DETAIL';
export const FETCHING_ARTICLE_DETAIL_BY_URL = 'FETCHING_ARTICLE_DETAIL_BY_URL';
export const FETCH_ARTICLE_DETAIL_SUCCESS = 'FETCH_ARTICLE_DETAIL_SUCCESS';
export const FETCH_ARTICLE_DETAIL_FAILURE = 'FETCH_ARTICLE_DETAIL_FAILURE';

// UPDATE READING HISTORY
export const UPDATING_READING_HISTORY = 'UPDATE_READING_HISTORY';
export const UPDATE_READING_HISTORY_SUCCESS = 'UPDATE_READING_HISTORY_SUCCESS';
export const UPDATE_READING_HISTORY_FAILURE = 'UPDATE_READING_HISTORY_FAILURE';

// FETCH USER HIGHLIGHT IN AN ARTICLE
export const FETCHING_HIGHLIGHT_ARTICLE = 'FETCHING_HIGHLIGHT_ARTICLE';
export const FETCH_HIGHLIGHT_ARTICLE_SUCCESS = 'FETCH_HIGHLIGHT_ARTICLE_SUCCESS';
export const FETCH_HIGHLIGHT_ARTICLE_FAILURE = 'FETCH_HIGHLIGHT_ARTICLE_FAILURE';

// REMOVE HIGHLIGHT
export const REMOVING_HIGHLIGHT = 'REMOVING_HIGHLIGHT';
export const REMOVE_HIGHLIGHT_SUCCESS = 'REMOVE_HIGHLIGHT_SUCCESS';
export const REMOVE_HIGHLIGHT_FAILURE = 'REMOVE_HIGHLIGHT_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';