# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hasBrain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'UserKit', :path => '../../mStage-UserKit-iOS-SDK'
  pod 'UserKitIdentity', :path => '../../mStage-UserKit-iOS-SDK'
  pod 'IQKeyboardManagerSwift', '4.0.13'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GoogleSignIn'

#pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

#pod 'react-native-wkwebview', :path => '../node_modules/react-native-wkwebview-reborn'

#pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  target 'hasBrainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
