# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hasBrain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'
  pod 'UserKit', :path => '../../mStage-UserKit-iOS-SDK'
  pod 'UserKitIdentity', :path => '../../mStage-UserKit-iOS-SDK'
  pod 'IQKeyboardManagerSwift', '4.0.13'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GoogleSignIn'

#pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

#pod 'react-native-wkwebview', :path => '../node_modules/react-native-wkwebview-reborn'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'hasBrainTests' do
    inherit! :search_paths
    # Pods for testing
  platform :ios, '9.0'
  end

end
