# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hasBrain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'UserKit', :path => '../../mStage-UserKit-iOS-SDK'
  pod 'UserKitIdentity', :path => '../../mStage-UserKit-iOS-SDK'
  pod 'IQKeyboardManagerSwift', '4.0.13'

  target 'hasBrainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
